# Generated by Django 3.0.4 on 2020-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('project_file', models.FileField(upload_to='files/project_file/')),
                ('additional_file', models.FileField(upload_to='files/additional_file/')),
                ('date_of_initiation', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
