# Generated by Django 3.0.4 on 2020-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_member_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='additional_file',
            field=models.FileField(null=True, upload_to='files/additional_file/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(null=True, upload_to='files/project_file/'),
        ),
    ]
