# Generated by Django 3.0.4 on 2020-03-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_member_mapping'),
        ('accounts', '0002_auto_20200328_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_description', models.TextField()),
                ('bug_file', models.FileField(upload_to='bug/files/')),
                ('bug_priority', models.CharField(max_length=15)),
                ('deadline', models.DateField()),
                ('reported_by', models.CharField(max_length=30)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
                ('target_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
