# Generated by Django 3.0.4 on 2020-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='job_title',
            field=models.CharField(max_length=30),
        ),
    ]
