# Generated by Django 3.0.4 on 2020-03-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200331_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip',
            field=models.CharField(max_length=6),
        ),
    ]
